### ISSUE TITLE
container view: bug with filtering commands that should be run in a specific tool

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#104]
From that devfile https://github.com/sunix/devfiles/blob/b45681a94ba8ce6e139cc4f453d7ce37c80435cf/che-in-che/che-theia-remote.devfile.yaml#L39-L96 , all the command but `run ... remote theia endpoint` should be executed on the tool `che-dev`, however the commands are displayed in every tools in the container view.
Filtering commands for a `dockerImage` tool works fine though.

![selection_188](https://user-images.githubusercontent.com/650571/53957604-09559880-40df-11e9-9c23-a44f794422dc.png)

**Comment by sunix** [comment]
I have had a look to this one and we have a problem for commands that are assigned to plugins tools:
- names are prefixed by 'dockerimage/' but we do compare exact values
- no command.attributes.machineName ... would have to use command.attributes.toolName
- command.attributes.toolName is not matching the name. For instance, i have a plugin tool named `dockerimage/theia-dev` but the command.attributes.toolName is `che-dev` (as defined in the devfile)

**Comment by mmorhun** [comment]
Fixed
