### ISSUE TITLE
Terminal API: sending text to the newly created terminal doesn't work as expected

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che-theia#111]
### Description
[`window.createTerminal`](https://github.com/theia-ide/theia/blob/b21023ef38060a127b0c152bdf71344de8950f59/packages/plugin/src/theia.d.ts#L3126) followed by [`terminal.sendText`](https://github.com/theia-ide/theia/blob/b21023ef38060a127b0c152bdf71344de8950f59/packages/plugin/src/theia.d.ts#L2340) leads to opening an empty terminal.

### Reproduction Steps
1/ Run the [terminal-plugin sample](https://github.com/eclipse/che-theia-samples/tree/master/samples/terminal-plugin) in Che Theia
2/ Call the `Send text to the terminal` command from the Command Palette.

#### Expected behavior:
New Terminal is created and text is printed to the terminal
![image](https://user-images.githubusercontent.com/1636395/54398444-be311c00-46c2-11e9-96dd-c38e9cb460a7.png)
**Note:** it works as expected in standalone Theia

#### Actual behavior:
New Terminal is created but the text isn't printed to the terminal
![image](https://user-images.githubusercontent.com/1636395/54398413-95a92200-46c2-11e9-862b-b96e70e5c32d.png)

**Comment by azatsarynnyy** [comment]
It's important for running the Kubernetes Tooling Che Plugin since a lot of the plugin's commands depend on these API calls.

**Comment by ashumilova** [comment]
Added to the next sprint with High priority. Thank you for notifying.

**Comment by sunix** [comment]
@AndrienkoAleksandr can we close this issue ?
