### ISSUE TITLE
VSCode extension installed but commands not available

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/che-theia#136]
I'm trying to validate Project Initializer in Che and faces the following issues:

Here is what I did:

- started che on minishift though chectl
- created a workspace using Che7 stack and theia-ide:next as editor
- installed `Project Initializer` extension with the `Plugin: Deploy plugin by Id` and the `vscode:extension/redhat.project-initializer` URL
- can't see an Project: related command in the command palette

**Comment by AndrienkoAleksandr** [comment]
Confirm this bug

**Comment by benoitf** [comment]
The issue has been fixed
