### ISSUE TITLE
Resize panels become broken and freezes when opened Welcome page...

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-theia#151]
We have a some strange bug. When opened 'Welcome Eclipse CHE page' resize left, right, and bottom panels doesn't work correctly. **When I close this widget - everyting works fine.** I guess it's some bug with web-view widgets... 

![CrazyResize](https://user-images.githubusercontent.com/6873095/55401453-77b03e00-5559-11e9-913f-7cc36421733f.gif)

**Comment by mmorhun** [comment]
Faced this issue too, pretty annoying, I would say.
