### ISSUE TITLE
Minor UI alignment issue with Welcome page tab icon

### ISSUE THREAD

**Issue by makandre** [eclipse/che-theia#174]
### Description
 

This is a very minor issue but as you can see in the below screenshot, the Welcome page tab icon is not aligned with the text (unlike the icon for editor tab which sits flush):

![image](https://user-images.githubusercontent.com/17596240/55987853-69a4a080-5c70-11e9-9328-21f99b0c02d7.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment]
Thanks for the report @makandre it has been fixed
