### ISSUE TITLE
"port is not exposed in the workspace as a server"

### ISSUE THREAD

**Issue by tetchel** [eclipse/che-theia#180]
### Description
When I try to launch a hosted plugin instance, I get the following popup:
![image](https://user-images.githubusercontent.com/8888438/56168846-56643e80-5faa-11e9-9275-d26552fac113.png)

I can then still access my new instance at `localhost:3030`, but my plugin does not appear in the Plugins view.

What does the above message mean? How do I fix it?

### Reproduction Steps

1. Build the docker image as detailed in the README
2. Run a che-theia container, eg:
`docker run -it -p 3100:3100 -p 3030:3030 -v "${THEIA_WORKSPACE}:/projects" eclipse/che-theia:next`
3. Run the "Hosted Plugin: Select Path" command and select my plugin folder.
4. Run the "Hosted Plugin: Start Instance" command (or restart if it's already running - doesn't matter).
5. The message shown above appears. 

The server still appears to start successfully, and I see a popup from my plugin saying it failed to activate, so the message might be a red herring (but my plugin still doesn't appear in the plugins view).

**OS and version:**    
macOS Mojave 10.14.4
Docker version 18.09.2, build 6247962

**Diagnostics:** 

Full logs:
[theia-logs.txt](https://github.com/eclipse/che-theia/files/3082245/theia-logs.txt)

**Comment by tetchel** [comment]
I tried it with https://github.com/eclipse/che-theia-samples/tree/master/samples/tree-view-sample-plugin and had the same result, so it's not my plugin.

**Comment by tetchel** [comment]
reading the logs I posted above, it looks like pretty much every request is failing, likely due to 

`root ERROR Uncaught Exception:  Unable to create Che API REST Client: "CHE_API_INTERNAL" is not set`
how to fix this?

**Comment by tetchel** [comment]
I will just develop against regular Theia for now... I think I am using this wrong.

**Comment by benoitf** [comment]
Hello @tetchel , I think you're trying to use the che-theia image outside of Che environment (Kubernetes, OpenShift, etc)
The che-theia image can't be run directly with docker. You need to use for example the Che cli to boot Eclipse Che https://www.eclipse.org/che/docs/che-7/che-quick-starts.html#running-che-locally_che-quick-starts
