### ISSUE TITLE
tasks: output of a command is not rendered correctly

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#192]
### Description
Executing che commands in che-theia with a che-theia task (from the container view or command palette `run tasks`), output is not looking good. special characters bash code for colors seems not to be taken in account. Also progress output are generating new lines when updated.
See screenshot:

![output](https://user-images.githubusercontent.com/5676062/57067089-b52df580-6cd6-11e9-956f-8214a89549e2.png)

### Reproduction Steps
- Open this devfile https://github.com/sunix/devfiles/blob/41ef94d8cff4964d99ebec0b5da0d3136d69e938/che-in-che/che-theia.devfile.yaml
- Start any che task like che:theia init

- Output is display but no colors and weird special characters are display

**OS and version:**    
Minikube and che7 nightly built version

**Comment by vparfonov** [comment]
Actually we wait on fix this epic https://github.com/eclipse/che/issues/11458 for replacing current output widget with terminal widget

**Comment by RomanNikitenko** [comment]
It was temporary solution to display output of a command to output channel. Within this [issue](https://github.com/eclipse/che/issues/11458) we depend on https://github.com/eclipse/che/issues/11442
I can provide a small improvement to fix this issue for output channel.
![output](https://user-images.githubusercontent.com/5676062/56742181-ea898f00-677c-11e9-9c66-a12f6bea12a5.png)

If it's OK that colors will not to be taken in account, I'll provide the PR
Then we switch task's output from output channel to terminal widget when https://github.com/eclipse/che/issues/11442 is resolved.

**Comment by AndrienkoAleksandr** [comment]
+1 for small improvements.

**Comment by sunix** [comment]
If it is a quick workaround, could you create the PR so we know what it is about ?

**Comment by sunix** [comment]
sorry I am reopening it as the workaround does not solve everything

**Comment by RomanNikitenko** [comment]
@sunix 
may be we should edit it like "switch task's output from output channel to terminal widget"
WDYT?

**Comment by sunix** [comment]
@RomanNikitenko I think we should not change the title, 'output of a command' is STILL not rendered correctly (no colors)
Maybe one of the PR to fix this would have the title you are suggesting but it is the difference between a bug/feature and tasks to fix/implement that.

**Comment by RomanNikitenko** [comment]
@sunix 
I think output channel is not designed for task output :-)
Are you sure a month ago we used output channel for task output?

btw: is screenshot actual at the moment?

**Comment by sunix** [comment]
@RomanNikitenko whatever what it was using ... it was working and now it is not so it is a regression.

**Comment by RomanNikitenko** [comment]
@sunix 
what about screenshot?

**Comment by RomanNikitenko** [comment]
@sunix 
So you think we should improve displaying colors for output channel instead of switching output of task to terminal widget when https://github.com/eclipse/che/issues/11442 is resolved
OK, I see.

**Comment by sunix** [comment]
No what I mean is that I don't mind the way it is fixed, but we have to fix that issue.

**Comment by sunix** [comment]
so not only about colors ... another example of how unreadable it is ATM:

output of task:
![Selection_249](https://user-images.githubusercontent.com/650571/57601488-e7541880-755c-11e9-8c06-6571765468ed.png)


versus terminal:
![Selection_250](https://user-images.githubusercontent.com/650571/57601496-ec18cc80-755c-11e9-876f-a1075c37140e.png)

**Comment by slemeur** [comment]
Outputs from Commands or Outputs from the terminal must be exactly rendered the same way

**Comment by sunix** [comment]
Super @AndrienkoAleksandr this is awesome :)
