### ISSUE TITLE
container view: move `New terminal`, commands and endpoints to the same level

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#196]
### Description
At the moment, for each container, actions and endpoints are in subfolders that force the user to unfold them to see them. Visually, it is also confusing when there are many containers
My proposal is to simplify the view, removing the folders `commands` and `endpoints` and move all of them in the same level of `New terminal` item.

Before:

![Selection_217](https://user-images.githubusercontent.com/650571/56822590-d82d5500-6851-11e9-97d0-dae083d0cab3.png)

After would look like:
![after](https://user-images.githubusercontent.com/650571/56822635-f430f680-6851-11e9-9c01-2c9b8fe00704.png)

**Comment by olexii4** [comment]
I think we should change the icon for "New terminal" to have a difference for each group.  Rename to "terminal". Use ' fa-tasks' for command icon instead of 'fa-terminal'.

And the last one. Add next logic: add group items if > 5 elements

**Comment by sunix** [comment]
terminal icon is good, but tasks ones ...
the endpoints icon has to be changed

About the logic to create group items, i don't think it is necessary.

**Comment by sunix** [comment]
what about

for tasks/che commands:
- fa-user-cog https://fontawesome.com/icons/user-cog?style=solid 

for endpoints:
- fa-external-link-alt https://fontawesome.com/icons/external-link-alt?style=solid  
- fa-rss https://fontawesome.com/icons/rss?style=solid for

**Comment by l0rd** [comment]
+1 for `fa-external-link-alt` for endpoints
+1 to have a separate icon for tasks but not sure if `fa-user-cog` is the good one

group item if > 5: maybe in a different task: let's make the first changes, get some feedback, and then iterate.

**Comment by sunix** [comment]
Looks like that now:

![Selection_221](https://user-images.githubusercontent.com/650571/57127290-372e2500-6d90-11e9-9ac6-16fc5590d69d.png)
