### ISSUE TITLE
Che in Che development is broken

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che-theia#198]
### Reproduction Steps
1. Create workspace from "Che 7 Theia dev" stack
2. Clone theia project
3. cd theia/
4. che:theia init -d
5. Build theia project

Result: build is failed
![che_theia_build](https://user-images.githubusercontent.com/5676062/56980581-658be480-6b85-11e9-821c-22424d987015.png)

**Comment by sunix** [comment]
fixed with https://github.com/eclipse/che-theia/pull/199

**Comment by RomanNikitenko** [comment]
Now I have another error:
![theia_error](https://user-images.githubusercontent.com/5676062/57507169-9f3bb880-7306-11e9-85f1-559ce31c11ed.png)

**Comment by sunix** [comment]
@RomanNikitenko https://ci.codenvycorp.com/job/che-theia-master-ci/

**Comment by sunix** [comment]
I am closing this issue because CI should help us detecting that kind of issue and we cannot open a issue each time the build is broken. Thanks.

**Comment by RomanNikitenko** [comment]
I'm sorry, but build is still broken. Maybe we can discuss here at least workaround or the cause of the problem

**Comment by RomanNikitenko** [comment]
I turned off [script](https://github.com/theia-ide/theia/blob/fe6ea99291c177a1ba9278b99c1918611f624bbf/dev-packages/electron/package.json#L31) for my assembly to get around the error

**Comment by sunix** [comment]
https://github.com/eclipse/che-theia/pull/215
