### ISSUE TITLE
Workspace API does not work properly

### ISSUE THREAD

**Issue by olexii4** [eclipse/che-theia#20]
After the last code cleanup for extensions/eclipse-che-theia-plugin-ext
https://github.com/eclipse/che-theia/commit/3f3e3cf9234e980f319e93c7b71386707a4fe051
workspace API does not work properly.

```
import * as che from '@eclipse-che/plugin';
...
const workspace = await che.workspace.getCurrentWorkspace();
console.log('>>>>>>>>>>> workspace', workspace);
```

This code sends the request, then gets a response with status code 200, but 'const workspace' always returns undefined.

That is why the containers plugin is not working properly
![screenshot from 2019-01-14 10-52-40](https://user-images.githubusercontent.com/6310786/51103263-bb14cf00-17ea-11e9-87bf-c6255f22d035.png)

**Comment by vitaliy-guliy** [comment]
@olexii4 have just checked with the latest changes. Everything's working on my side.

**Comment by vitaliy-guliy** [comment]
Containers plugin is also working.
![screenshot from 2019-01-14 12-21-28](https://user-images.githubusercontent.com/1655894/51107299-1220a100-17f7-11e9-88af-ec48ba039ac5.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/12417

**Comment by olexii4** [comment]
@vitaliy-guliy  You tested it locally with docker infrastructure.
