### ISSUE TITLE
Clean up theia-endpoint-runtime directory structure

### ISSUE THREAD

**Issue by tsmaeder** [eclipse/che-theia#200]
The folder dockerfiles/theia-endpoint-generator contains actually 3 things:

1. Docker stuff to build the theia endpoint runtime docker image
2. A nodejs application that starts a version of theia that only runs a plugin endpoint (starting with plugin-remote.ts)
3. A theia extension that handles discovery of locally installed plugins and routes messages to/from those plugins.

Having all those concerns mixed in the same directory structure makes it difficult to understand what is going on in the code and prevents us from separating generally useful code from the Che specific stuff.

We should do two things:

1. Separate the plugin endpoint theia extension to extensions/plugin_endpoint
2. Separate the nodejs application to it's own root level folder

Running plugins in multiple plugin host processes seems like something that we might even contribute back to the main theia project if we structure the code correctly.

**Comment by tsmaeder** [comment]
Adding label "invalid", because we don't have a label for "software architecture".

**Comment by AndrienkoAleksandr** [comment]
> software architecture
Ok, I applied label "software architecture"

**Comment by benoitf** [comment]
The remote extension was before a separate extension in a separate repository and @tolusha from your team moved it to docker folder part so it seems there is a lack of consistency in what you're describing.

AFAIK it was intentional to keep this extension part of Eclipse Che without putting it in Theia.

**Comment by tsmaeder** [comment]
So I guess he moved it to the wrong directory. 

> AFAIK it was intentional to keep this extension part of Eclipse Che without putting it in Theia.

What was intentional? I don't object to this being in the che-theia repo, but to it being all in the same directory and in the "dockerfiles" dir.

**Comment by benoitf** [comment]
@tsmaeder intentional to have this extension in che-theia and not theia.
