### ISSUE TITLE
DeprecationWarning: Tapable.apply is deprecated.

### ISSUE THREAD

**Issue by monaka** [eclipse/che-theia#213]
### Description

DeprecationWarning is shown in `@eclipse-che/theia-assembly`. 
It looks this is not critical.

### Reproduction Steps

Builds 08df279dc3ec32b25b8cb2fb78e432c2e43c052c

**Diagnostics:** 

Build log.
```
@eclipse-che/theia-assembly: $ theia build --mode production --config cdn/webpack.config.js --env.cdn=./cdn.json --env.monacopkg=@typefox/monaco-editor-core@0.14.6 --env.monacohtmlcontribpkg=monaco-html@2.2.0 --env.monacocsscontribpkg=monaco-css@2.2.0 && yarn run override-vs-loader
@eclipse-che/theia-assembly: (node:9972) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
```

**Comment by benoitf** [comment]
Hello,
I would say it should be opened against theia repository

**Comment by monaka** [comment]
@benoitf I see. I checked the vanilla Theia and reproduced this. I close this and will open the issue there.
