### ISSUE TITLE
Nightly builds working?

### ISSUE THREAD

**Issue by monaka** [eclipse/che-theia#226]
### Description

```
$ docker run -it eclipse/che-theia-dev:nightly -- node -v
v8.12.0
```

Too old. Should be 10.15.

https://github.com/eclipse/che-theia/blob/e7ec889793ff326e25e053667258da531f501106/dockerfiles/theia-dev/Dockerfile#L14

### Reproduction Steps

See `Description` above.

**Comment by benoitf** [comment]
Hello,

We are using `:next` tag on every commit instead of nightlies now

**Comment by monaka** [comment]
@benotif I see. If so, I think it's better to fix some `nightly` in the master branch.

https://github.com/eclipse/che-theia/blob/eb6a6dacbfb55a6c799a4e26289b7c291bc1b906/dockerfiles/build.include#L44
