### ISSUE TITLE
Can not run launch configuration

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che-theia#233]
### Reproduction Steps
1. Create workspace using Che 7 Theia dev stack
2. Turned on Node debug and Node debug (legacy) plugins
3. Start workspace, clone and build theia project
4. Change port  for 'Launch Backend' configuration 3000 ---> 3130
5. Run 'Launch Backend' configuration

**Comment by tolusha** [comment]
It seems OOM error, try to add
```
    "sidecar.ms-vscode/node-debug.memory_limit": "256Mi",
    "sidecar.ms-vscode/node-debug2.memory_limit": "500Mi",
```
