### ISSUE TITLE
Bug with an empty containers tree

### ISSUE THREAD

**Issue by olexii4** [eclipse/che-theia#25]
The empty containers tree. And it can happen periodically after restarting the current workspace.

Subtask/PR:
- [x] Fix a getWorkspace method for the container plugins.￼ https://github.com/eclipse/che-theia/pull/32. 
- [x] Treeview api https://github.com/theia-ide/theia/issues/4122 duplicate of https://github.com/theia-ide/theia/issues/3907

**Comment by olexii4** [comment]
Add logs and see sometimes an empty tree after workspace starting, in the case when process.env.CHE_MACHINE_TOKEN is undefined

https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts#L90 

Is not clear. Need to investigate more. Add several tries and a delay
https://github.com/eclipse/che-theia/pull/32/files#diff-c30cdeeaee19f3e90d03ade32754d4e3R32

**Comment by olexii4** [comment]
Depends on
https://github.com/theia-ide/theia/issues/4122

**Comment by sunix** [comment]
subtasks:
- [ ] Fix a getWorkspace method for the container plugins.￼" - was mark as DONE in daily stand-up. 
- [ ] Treeview api https://github.com/theia-ide/theia/issues/4122 duplicate of https://github.com/theia-ide/theia/issues/3907
