### ISSUE TITLE
Build own che-theia image 0.7.0

### ISSUE THREAD

**Issue by lamgibrcom** [eclipse/che-theia#265]
### Reproduction Steps
After che:theia init -c ../che-theia-init-sources.yml
the yarn command fails with :

Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/stoplightio/moxios.git
Directory: /theia-source-code
Output:
fatal: read error: Operation timed out

**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment]
hello @lamgibrcom do you have some firewall issues ?

**Comment by lamgibrcom** [comment]
Yeah it is ! the git prot is blocked. thanks @benoitf
