### ISSUE TITLE
Update Theia image to the newer version (for example 0.3.19)

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-theia#39]
Task: Update Theia to the version 0.3.19

**Comment by AndrienkoAleksandr** [comment]
First should be fixed https://github.com/eclipse/che-theia/issues/29 and https://github.com/eclipse/che-theia/issues/37

**Comment by l0rd** [comment]
I think the plan is to:
- [ ] build 2 che-theia versions in the CI: one using latest upstream theia and the other nightly theia
- [ ] publish 2 theia editor versions in the plugin registry

Am I right? Is this issue tracking both tasks? cc @evidolob

**Comment by evidolob** [comment]
@l0rd Yes, you are right

**Comment by l0rd** [comment]
@evidolob can we keep this issue open until we have 2 versions of Theia in `https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.editor.theia/` ? Or is there another issue to track that?
