### ISSUE TITLE
Build and package che-theia plugins during che-theia image build.

### ISSUE THREAD

**Issue by sunix** [eclipse/che-theia#45]
The same way we are building extensions, we would build che-theia plugins from sources and package them so they are available right away.

1. skate board step: https://github.com/eclipse/che-theia/pull/43 
2. moto cycle step: include che-theia plugins build into the `che:theia` generator
    - `che:theia init` would also clone plugins projects
        ```
        ${theia}/che/<clone ext/plugins repos>
        ${theia}/packages/<ln -s extensions>
        ${theia}/plugins/<ln -s plugins>
        ```

- [x] it would use a single `extensions.yml` file. we would specify which project is plugin:
         -  move `extensions/extensions.yml` to `che-theia-init-sources.yml`
         -  renamed `folders` to `extensions` , root `extensions` to `sources` and adding new folders for plugins: `plugins`
- [x] build all the plugins `${theia}/plugins` with a single command: provides a script located in plugins folder that would perform `yarn` on each plugins.
- [x] packaging the future content of `/default-theia-plugins/`: the script `foreach_yarn` is also copying the .theia files in production/plugins folder.
- [x] update CI https://github.com/eclipse/che-theia/pull/201

**Comment by benoitf** [comment]
I like the proposal

probably rename `extensions.yml` to a more generic name (as for now extensions.yml was only for extensions)

I think we can avoid default (no need of compatibility AFAIK)

**Comment by AndrienkoAleksandr** [comment]
+1 For generic name.

**Comment by sunix** [comment]
- `che-theia-customizations.yml` ?
- `customizations.yml` ?

**Comment by sunix** [comment]
currently testing to build theia (after che:theia init) with symb links that i added manually to plugins but got this issue:
```
[compile] yarn compile exited with code 0
Packaging of plugin
🔍 Validating...✔️
🗂  Getting dependencies...❌️
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/projects/theia/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  killed: false,
  stdout: '$ yarn clean && yarn build && yarn lint:fix && yarn test\n$ rimraf lib\n$ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile" && theia:plugin pack\n[compile] $ tsc\n[lint] $ tslint -c ../../configs/tslint.json --project tsconfig.json\n[format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json\n[format] yarn format exited with code 0\n[lint] yarn lint exited with code 0\n[compile] yarn compile exited with code 0\nPackaging of plugin\n🔍 Validating...✔️ \n🗂  Getting dependencies...❌️ \ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: '=> 🚒 Unable to execute the command yarn list --json --prod: Error: Command failed: yarn list --json --prod\n{"type":"error","data":"Command failed.\\nExit code: 1\\nCommand: git\\nArguments: pull\\nDirectory: /usr/local/share/.cache/yarn/v2/.tmp/b0c6bf631ee9ab7b12cce07c427c070c\\nOutput:\\nYour configuration specifies to merge with the ref \'refs/heads/master\'\\nfrom the remote, but no such ref was fetched."}\n\nerror Command failed with exit code 1.\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepare',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
```
I guess it is the symbolic link is `hidding` the .git folder and git commands are performed against the theia repo and not the plugin repo.
