### ISSUE TITLE
How is eclipse/che-theia different from eclipse/che?

### ISSUE THREAD

**Issue by dclong** [eclipse/che-theia#52]
And how do I run the Docker image?

**Comment by benoitf** [comment]
Hello dclong.
eclipse/che-theia is the customized version of Theia that runs smoothly in Che (like terminals being aware of containers of the workspace), icon to go the dashboard, etc
But it's only the IDE/Editor part.

You still need Eclipse Che to run this CheTheia, it is done by selecting the plugin "theia" in a Che7 Workspace
