### ISSUE TITLE
Revisit name of docker images

### ISSUE THREAD

**Issue by benoitf** [eclipse/che-theia#63]
Before, images were in che repository.
and it was tagged with 'theia version' and 'che version'
 - che-theia:0.3.18-6.17.2 (theia version being 0.3.18 and che version being 6.17.2)
 - che-theia:0.3.19-nightly (theia 0.3.19, nightly build of the image)

but now, che-theia images are published from che-theia repository and we need to revisit labels because `nightly` images are not every night (but at each commit), etc.

Here is some proposal to discuss:
 - 0.3.19-latest:  latest 'stable' version 
 - latest: an alias to 0.3.19-latest
 - next: using upstream of theia when building the image
 - next-nightly: every day result of upstream theia + upstream of che-theia

(theia is already using `next` keyword for their current `upstream` version)

cc @l0rd @evidolob

**Comment by l0rd** [comment]
At every commit in che-theia you build the following 2 images right?
- stable upstream theia + head of master che-theia
- master upstream thaia + master che-theia

The second one is `next`. What's the name of the first one? We can use the commit hash as well (e.g. `<commit-upstream>-<commit-che-theia>`) and tag `latest`, `next` and `next-nightly` as you mentioned).

**Comment by benoitf** [comment]
We should probably have branches in che-theia repository
- one branch for each upstream theia version like 0.3.19 branch
- master branch for upstream master.
so every commit shouldn't trigger the build. Only a commit in the right branch.

Commit hash are interesting if we want to get back on version. Do we need them ?

**Comment by l0rd** [comment]
I don't know about 2 branches. You will need a `next` branch if upstream theia introduces a breaking change and you want to provide a fix without affecting `master`. But my question was: what will be the tag for the image build after every commit (stable theia + master che-theia)?

> Commit hash are interesting if we want to get back on version. Do we need them ?

No I don't think so. Maybe hash are useless after all.
